### ISSUE TITLE
[REQ] Translations

### ISSUE THREAD

**Issue by CYBERC4T** [K4ryuu/K4-System#1]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I would like to see in the configuration file settings of all phrases from the chat, it will allow everyone to customize phrases for themselves, because not everyone has English-speaking servers

**Comment by K4ryuu** [comment]
Greetings,
I'm waiting for the CSS standard for Translations. I see currently no point in that developing it until the standard, but if it's urgent for anyone I will haha

**Comment by K4ryuu** [comment]
Greetings,
Translations is being added in the next patch with CSS standards.
Thank you for the patience.
