### ISSUE TITLE
!rank

### ISSUE THREAD

**Issue by asdfxD** [K4ryuu/K4-System#10]
hi,

it's me again :D

!rank command doe not do anything, is it because of cs2fixes installed? i had your old version K4ryuuSimpleRanks before and !rank trigger was working with current cs2fixes.

edit: all triggers are working except !rank

edit 2: cssharp colors are wrong. LightBlue = Lila

**Comment by K4ryuu** [comment]
Greetings,
I was unable to reproduce your bug, so you should check that in the next update (above v1.2), which is going to be uploaded shortly.

The colors are not from the plugin. They are from CSS.

If your problem exists in the next update, please reopen this issue.
