### ISSUE TITLE
[REQ] Hide automatic chat messages

### ISSUE THREAD

**Issue by Marfeld** [K4ryuu/K4-System#100]
Is there a way to hide automatic chat messages?
I find this really annoying in the chat.

And what exactly does the settings do:
"lvl-ranks-table": false,
"dynamic-death-points": true,
"dynamic-death-points-max-multiplier": 3,
"dynamic-death-points-min-multiplier": 0.5

Greetings Mario

**Comment by TianxSky** [comment]
"spawn-message": false,

**Comment by Marfeld** [comment]
<img width="434" alt="Screenshot 2023-12-31 162034" src="https://github.com/K4ryuu/K4-System/assets/154004296/4ec6b7e7-f630-4be3-a433-7128afb36e56">

I mean these messages. It would be great if you could turn this off.
And it would be nice if you could also see headshots and KD in !stats.

**Comment by K4ryuu** [comment]
Greetings,
You can optionally set `round-end-points` to `true`, which is going to print only one summary of the points changes per round. This is going to prevent the spam of the points.

If you have any other problem/idea about this or you are not satisfied by my answer, feel free to reopen the issue and we discuss it further.

Best Regards,
K4ryuu
