### ISSUE TITLE
[BUG] Timers stats

### ISSUE THREAD

**Issue by csportalsk** [K4ryuu/K4-System#103]
`CSSv142  - K4-System v3.0.4
`
Timer stats for players are counted wrong. 
all - 597, ct - 0, t - 99, spec - 0, dead - 0, alive - 114

Every player seems to have different.
all - 283, ct - 283, t - 0, spec - 0, dead - 48, alive - 41

**Comment by csportalsk** [comment]
When player again connected to the server timer stats are reseted and strats from 0 for player.

**Comment by K4ryuu** [comment]
This problem was fixed with the 3.1.0 version, but I've forgotten to close the issue haha
