### ISSUE TITLE
[BUG] `lastconnect` column

### ISSUE THREAD

**Issue by mrdiega** [K4ryuu/K4-System#104]
In the `lvl_base` table, the `lastconnect` column shows the same value for all players
![image](https://github.com/K4ryuu/K4-System/assets/79888956/06e1aa7a-1cc8-4124-9ddc-7dfe570f6fcd)
K4-System v3.0.4

**Comment by K4ryuu** [comment]
Greetings,
I think your problem has been fixed by @stefanx111 with the #111 Pull Request. This update will be published tonight after I finish the rest of the update.

Appreciate your issue!
