### ISSUE TITLE
!gloves [REQ]

### ISSUE THREAD

**Issue by YouZA9123** [K4ryuu/K4-System#109]
**Is your feature request related to a problem? Please describe.**
No.
**Describe the solution you'd like**
Add !gloves to the lugin
**Describe alternatives you've considered**
Add !agent maybe.

**Additional context**

**Comment by K4ryuu** [comment]
Hello,
I appreciate your time in opening an enhancement request. However, I regret to inform you that I cannot add this feature due to its violation of Steam's Terms of Service.

Sincerely,
K4ryuu
