### ISSUE TITLE
[BUG] lvl_base playtime column

### ISSUE THREAD

**Issue by mrdiega** [K4ryuu/K4-System#121]
The `playtime` column in the lvl_base table displays the incorrect number of seconds played on the server. For some players, the number of hours played reached 5000 within a few days of play. I tried resetting this column, but it didn't help
![image](https://github.com/K4ryuu/K4-System/assets/79888956/e8417ea1-36ea-4210-ac20-540eb6611428)
K4-System v3.1.2, css 154

**Comment by K4ryuu** [comment]
playtime is in seconds

**Comment by mrdiega** [comment]
> playtime is in seconds

12029234 seconds = 3341 hours
In just a few hours of play

**Comment by Cruze03** [comment]
I faced the same.
Changing line 141 in "Module/Time/TimeFunctions" to the following fixed it:
``playtime` = '{playerData.TimeFields["all"]}',`

**Comment by K4ryuu** [comment]
The problem has been solved and uploaded with v3.1.3.
Appreciate your contribution @Cruze03
