### ISSUE TITLE
[REQ] Daily Challenges

### ISSUE THREAD

**Issue by asapverneri** [K4ryuu/K4-System#123]
I got an idea from one of our players. They'd like some kinda of "Daily Challenges"  and when completed they get x amount of points in return.
ex. get 50 kills, play 1 hour, play on CT side x amount of time or something similar.

It could notify player when connecting that there is daily challenge running/available.

**Comment by K4ryuu** [comment]
https://www.buymeacoffee.com/k4ryuu/e/212956
