### ISSUE TITLE
[ENHANCEMENT] Note the plugin is deactivated due to not enough players

### ISSUE THREAD

**Issue by jinnixyz** [K4ryuu/K4-System#127]
possible to add a message that appears as soon as the plugin is disabled due to too few players? my idea was:

"general-settings": {
"spawn-message": true,

X "plugindisabled-message": true,  X

"module_ranks": true,
"module_stats": true,
"module_times": true,
"lvl-ranks-table": false,
 "ffa-mode": false

"k4.general.plugindisabled-message": "Plugin disabled. Players required : 1/4

The message appears after every round when spawning, so the players know that they are currently not getting any points because there are not enough players on the server.

**Comment by K4ryuu** [comment]
Greetings,
The requested feature is being added in the upcoming update. Thank you!

**Comment by K4ryuu** [comment]
Hello,
The request has been solved and will be uploaded with the upcoming release.
Thank you!
