### ISSUE TITLE
[ENHANCEMENT] Player name on kills and deaths

### ISSUE THREAD

**Issue by iclassdon** [K4ryuu/K4-System#128]
Optional feature.  Add player name on kills and deaths.  i.e. reformatted text lines below:

On death: 
[K4-System] -2 points for dying to Player (1000 points)
or 
[K4-System] Points: 27169 [-5] for dying to Player

On kill:
[K4-System] +10 points for killing Player (1010 points) 
or
[K4-System] Points: 27169 [+8] for killing Player

**Comment by K4ryuu** [comment]
Hello,
This feature is going to be added in the next update with a new config option to not to force everyone to use it.

**Comment by K4ryuu** [comment]
Greetings,
The requested enhancement has been solved and will be available in the upcoming release.
Thank you!
