### ISSUE TITLE
[REQ] Ranks tag

### ISSUE THREAD

**Issue by daffyyyy** [K4ryuu/K4-System#13]
**Additional context**
Adding tags for ranks, e.g. Global Elite  is too long for scoreboard but GE is not.

```
	"Global Elite": {
		"Tag": "GE", // From this amount of experience, the player is Silver
		"Exp": 1680, // From this amount of experience, the player is Silver
		"Color": "Gold" // Color code for the rank. Find color names here: https://github.com/roflmuffin/CounterStrikeSharp/blob/main/managed/CounterStrikeSharp.API/Modules/Utils/ChatColors.cs
	},
```

**Comment by K4ryuu** [comment]
Greetings,
The feature has been implemented into my dev build. It will be publishes shortly, when all the issues are solved. 
Thank you for the request.

Quick review:
![CleanShot 2023-11-16 at 20 13 12@2x](https://github.com/K4ryuu/K4-System/assets/104531589/c4eff532-165a-4b6e-82c8-812c405bdaa6)


Best Regards,
K4ryuu
