### ISSUE TITLE
[BUG] !admins

### ISSUE THREAD

**Issue by asapverneri** [K4ryuu/K4-System#131]
!admins shows two groups when i've granted myself with just one ("#css/owner"). 
I have "#css/owner" as owner and "#css/admin" as regular admin and it shows me twice (just like im in both groups when im not). People who's granted with "#css/admin" show up correctly in the list. 

- OS: Ubuntu
- CSS Version v154 (I'll update)
- Plugin Version v3.1.4 (I'll update)

**Comment by K4ryuu** [comment]
Greetings,
The problem has been solved and will be published in the upcoming release.
