### ISSUE TITLE
[BUG] Your data is not yet loaded. Please try again later

### ISSUE THREAD

**Issue by GrishaKosak** [K4ryuu/K4-System#133]
**Describe the bug**
Hello, I have been using the plugin for a long time, unfortunately for several versions I have had a problem with the message in the title, I deleted the config and re-filled it, unfortunately it is still the same. I removed SQL, still the same. The title message appears with the !rank etc. command

**Logs/Screenshots**
[Please attach logs or screenshots if available.](https://i.ibb.co/R9CsH6Q/rank.png)

**Comment by Sandy-Garrido** [comment]
I think this usually means there may be an issue connecting to the database.
Are you receiving any server logs from K4 around database connections/mysql?

**Comment by GrishaKosak** [comment]
hey. I dont have any issue with SQL. I also using SQL from cs2 server to another plugins, and everything is ok.

**Comment by K4ryuu** [comment]
Greetings,
Today I'm going to check the problem, but most probably connected to #134

**Comment by K4ryuu** [comment]
The problem has been solved hopefully with the latest release, but if you encounter the problem again, please re-open this issue.
