### ISSUE TITLE
Hide automatic notifications

### ISSUE THREAD

**Issue by Marfeld** [K4ryuu/K4-System#139]
Could you add in the config that you can deactivate all automatic messages in the chat, so that no summary is displayed.
I would think it would be nice if only at the request of the player, e.g. !rank/!stats etc. messages would come.
I also find it more pleasant to text with my fellow players when the chat isn't so full.

Or that every player who wants to could deactivate this themselves via the chat and it will remain saved until they change it again, e.g. "!message off" or something like that. That would be a dream

Greetings Mario

**Comment by K4ryuu** [comment]
The message amount while using round end summary is really low (one per round) so personally I think this feature wouldn't make sense.
