### ISSUE TITLE
[REQ] Opt In for the print every round

### ISSUE THREAD

**Issue by DigitalFriends** [K4ryuu/K4-System#14]
Could we get an option in the config where we can change the print for players upon gaining points?
Would be great to have these options:
- Disable point print 
- Only print points changed at round end
- Only print points changed at map end
- Print points changed immediately

**Comment by K4ryuu** [comment]
![CleanShot 2023-11-16 at 22 35 33@2x](https://github.com/K4ryuu/K4-System/assets/104531589/9df1c29a-63ef-4621-866f-76f9b8b3febe)

Greetings,
I have opted in a Round End summary with a new config to decide when to print the point changes.
Thank you for the request!

Best Regards,
K4ryuu
