### ISSUE TITLE
[BUG] Min players BUG

### ISSUE THREAD

**Issue by shaikhnedab** [K4ryuu/K4-System#140]
**Describe the bug**
K$-System giving points when I am alone one the server even when `minimum-players` is set to 2

**Logs/Screenshots**
![20240222151950_1](https://github.com/K4ryuu/K4-System/assets/55206494/55d18acb-f800-43bb-8628-ac9566774668)

Environment
- CSS Version [168]
- Plugin Version (3.3.9)
- Configs 
![image](https://github.com/K4ryuu/K4-System/assets/55206494/11499c26-f276-4cc8-9187-2ce8014f4f1c)

```  id     time ping loss      state   rate adr name
65535 [NoChan]    0    0 challenging      0unknown ''
65535 [NoChan]    0    0 challenging      0unknown ''
65535 [NoChan]    0    0 challenging      0unknown ''
65535 [NoChan]    0    0 challenging      0unknown ''
65535 [NoChan]    0    0 challenging      0unknown ''
65535 [NoChan]    0    0 challenging      0unknown ''
65535 [NoChan]    0    0 challenging      0unknown ''
65535 [NoChan]    0    0 challenging      0unknown ''
65535 [NoChan]    0    0 challenging      0unknown ''
65535 [NoChan]    0    0 challenging      0unknown ''
65535 [NoChan]    0    0 challenging      0unknown ''
  11    04:43    2    0     active 786432  'Shaikh Kebab'
#end

**Comment by K4ryuu** [comment]
The problem is being fixed within the next release. 
Thank you!

**Comment by everkk** [comment]
I still have this problem

**Comment by everkk** [comment]
When map has been changed its works. But when is more than 4 players and someone disconnect, plugin still giving points.

**Comment by K4ryuu** [comment]
Possible fixed the problem with `p.Connected == PlayerConnectedState.PlayerConnected` in the upcoming release.
I dont close the issue, but please give a feedback from `4.0.0` version.
Thank you!

**Comment by K4ryuu** [comment]
I close the issue because of inactivity.
That means for me it's fixed.
