### ISSUE TITLE
[ENHANCEMENT] Point for the CT team to defuse C4

### ISSUE THREAD

**Issue by crashzk** [K4ryuu/K4-System#141]
We currently have the following options to earn points with the C4.
```
    "bomb-drop": -1,
    "bomb-pickup": 1,
    "bomb-defuse": 1,
    "bomb-plant": 1,
    "bomb-explode": 1,
``` 

In the case of `bomb-plant` the player who plants the c4 wins a point, and `bomb-explode` the entire TR team wins a point.

Would it be possible to apply this feature to CT defuse? In other words, whoever defuses C4 gets a point but has the option for the entire CT team to get a point.

```
    "bomb-defuse": 2,
    "bomb-defuseall": 1,
```
In the example above, the CT that defused gains two points and the CT team gains 1 point for the C4 defuse.

**Comment by K4ryuu** [comment]
Feature has been added and will be published with the upcoming release.
Thank you!
