### ISSUE TITLE
[BUG] Points and stats not saving in database, after map change.

### ISSUE THREAD

**Issue by GreeNyTMs** [K4ryuu/K4-System#151]
**Describe the bug**
Rank system working, like /ranks, etc.. But sometimes it not saving points into database, same kills, stats.. But command
working. In chat i didnt see messages, that i getting points for kills, assists. I think its propably happenes after map change.

**To Reproduce**
I restarted a server

**Expected behavior**
Saving points and stats to database. And it worked.

**Logs/Screenshots**
https://imgur.com/l77M0bY

**Environment (please complete the following information):**
- OS: Linux
- CSS Version: 195
- Plugin Version: 3.3.9

**Comment by K4ryuu** [comment]
Use the latest version.
With that currently there are no reported bugs.
