### ISSUE TITLE
ajouter les admins

### ISSUE THREAD

**Issue by TWD31200** [K4ryuu/K4-System#154]
bonjour 
je souhaiterais savoir comment ajouter des admins avec k4 sachant que j'utilise déjà simple admins 
merci de votre aide

**Comment by K4ryuu** [comment]
I don't speak this language. 
I close the issue.

**Comment by weeestar** [comment]
you just need to add the flags to your admins config file.
tu dois ajouter les flags dans ta config admin.

@K4ryuu he wanted to know how to manage K4system with simple admin
