### ISSUE TITLE
Server crash [BUG]

### ISSUE THREAD

**Issue by GravityUA** [K4ryuu/K4-System#16]
Server crash, reason: when CT defuses a bomb and doesn’t have time, the server crashes, if you have time to defuse the bomb or just wait for the explosion, then everything is fine

**Comment by K4ryuu** [comment]
Greetings,
I was unable to reproduce your crash.
In the last 3 seconds, I started to defuse, you the bomb exploded. 
No crashes caused by that.

**Comment by GravityUA** [comment]
I recorded a video for you of how I get a server crash https://youtu.be/8Us7u071Wvc
