### ISSUE TITLE
[BUG] Dont see all ranks

### ISSUE THREAD

**Issue by everkk** [K4ryuu/K4-System#160]
**Describe the bug**
Hello i dont see all ranks on tab on my server. Some people see all ranks rights.

**To Reproduce**
Use with cs2 retakes https://github.com/B3none/cs2-retakes

**Expected behavior**

**Logs/Screenshots**
![image](https://github.com/K4ryuu/K4-System/assets/67241375/0cf24cf1-88e6-4557-9061-d67d66a43a87)
![image](https://github.com/K4ryuu/K4-System/assets/67241375/afc5819d-4158-4714-aa19-053ba3b6777d)
![image](https://github.com/K4ryuu/K4-System/assets/67241375/7cdb0517-4c14-4b13-ab77-609aa0618c3b)

**Comment by everkk** [comment]
On second server i have same problem, but i see ranks properly in halftime.

**Comment by K4ryuu** [comment]
Hello,
1. This is not in K4-System
2. Read about the problem first, since it's not a bug and a known thing: https://github.com/K4ryuu/K4-System-MMRanks/issues/1#issuecomment-2022322325

Best Regards,
K4ryuu
