### ISSUE TITLE
[FEATURE] Web Interface for displaying server statistics

### ISSUE THREAD

**Issue by aronmgv** [K4ryuu/K4-System#161]
Hey,

I cant seem to find on roadmap whether Web Interface is planned to display server collected statistics.. Or is there an external app which could display them? I understand it would need to connect your database.. 

Thanks!

**Comment by K4ryuu** [comment]
Hello,
If you had read the wiki, you would have known that there are web interfaces created for the K4-System, and all LVLRank web interfaces from CS:GO can be used with it.

https://github.com/K4ryuu/K4-System/wiki

Best Regards,
K4ryuu

**Comment by aronmgv** [comment]
Sorry for my lackness.. I read that wiki page but missed that.. it was 3am for me. Thanks!
