### ISSUE TITLE
[ENHANCEMENT] Separate ranks and country codes

### ISSUE THREAD

**Issue by hks27d** [K4ryuu/K4-System#163]
**Describe the enhancement**
Separating rank rags and country codes for more space in scoreboard

**Problem and motivation**
Too much space consumed in scoreboard by having both rank tags and country codes enabled at the same time.

**Suggested solution**
Separate rank tags and country codes, giving each one an option to enable or disable it. Let the servers choose which one it's displayed in scoreboard. Those who want them both could enable them by setting both options to "true".

**Alternatives**
No alternative solutions.

**Additional context**
In order to have country codes enabled we must enable rank tags as well. That's not good for servers who have players with long names in scoreboard.

**Comment by K4ryuu** [comment]
Greetings,
The enhancement has been made and it is going to be released shortly as an experimental version, because it changed too much.
