### ISSUE TITLE
[BUG] !listadmins bug

### ISSUE THREAD

**Issue by hardixnph** [K4ryuu/K4-System#164]
**Describe the bug**
I have 3 groups on my server and when I type !listadmins I appear in all groups

**To Reproduce**
Create 3 groups and use these settings in config https://files.baroy.net/Code_gudKSKz5i9.png

**Expected behavior**
To appear in only one group

**Logs/Screenshots**
https://files.baroy.net/cs2_qH9YewGA4r.png

**Environment (please complete the following information):**
- OS: Debian 11
- CSS Version: v204
- Plugin Version: 4.0.4 (release)
- Configs: https://files.baroy.net/Code_gudKSKz5i9.png

**Additional context**
Nothing

**Comment by K4ryuu** [comment]
The problem has been fixed and it is going to be released shortly as an experimental version, because it changed too much.
