### ISSUE TITLE
[BUG] the ranks not sabing on database

### ISSUE THREAD

**Issue by rodopoulos1** [K4ryuu/K4-System#165]
**Describe the bug**
ranks not saving on db since 4.0.0 for me

**To Reproduce**
Kill player e see your rank in chat and db, appear none

**Expected behavior**
The ranks to work

**Logs/Screenshots**
![image](https://github.com/K4ryuu/K4-System/assets/101236856/5e1f2adb-ac8f-4b0e-90d0-81f1c7639d58)
![image](https://github.com/K4ryuu/K4-System/assets/101236856/6152a20a-0a76-42d0-8736-504ac0c4aea8)
![image](https://github.com/K4ryuu/K4-System/assets/101236856/833634b5-5cc7-4181-aa3d-e38be4747496)

**Environment (please complete the following information):**
- OS: ubuntu
- CSS Version 202
- Plugin Version 4.0.4 (dont works since 4.0.0

**Comment by K4ryuu** [comment]
The problem has been solved in the latest release (4.1.0)
Thank you

**Comment by rodopoulos1** [comment]
now i having this porblem idk if its related (plugin is starting)

  having this error on your plugin and ⁠[CS2] Store (0.1.2) plugin, what is this?
  
  
![image](https://github.com/K4ryuu/K4-System/assets/101236856/5a13bb2c-8d49-4d2e-a649-d284b9215139)
