### ISSUE TITLE
Bug top and server lagging with a error on k4

### ISSUE THREAD

**Issue by rodopoulos1** [K4ryuu/K4-System#166]
!top is bugged

position 6

![image](https://github.com/K4ryuu/K4-System/assets/101236856/c64fa6ab-35a2-4c3f-b2e3-fce175dffc39)

About that top only updates when change map idk why

----------------------------------------

Server is lagging with that:
![image](https://github.com/K4ryuu/K4-System/assets/101236856/7fcace86-ec91-4826-be5e-b002ca25d544)

**Comment by K4ryuu** [comment]
All three problem has been solved and being published shortly.
Thank you
