### ISSUE TITLE
[BUG] Commands related to disabled modules are included in the output

### ISSUE THREAD

**Issue by hks27d** [K4ryuu/K4-System#169]
**Description of the bug**
The commands related to the disabled modules should not be included in the output when typing css_k4 in console or !k4 in chat.

**How to reproduce the bug**
Set these modules to false in the config and restart the server:
- `"module_stats": false,`
- `"module_utils": false,`

The commands related to stats and utils are still showed when typing css_k4 in console or !k4 in chat.

**Expected behavior**
Setting the options to false must also disable their corresponding commands when typing css_k4 in console or !k4 in chat.

**Environment:**
- CSSharp 213
- K4-System v4.1.6
- Specific settings in config: `"module_stats": false,` and `"module_utils": false,`

**Comment by K4ryuu** [comment]
This bug has been fixed and going to be published in the upcoming release. Thank you!
