### ISSUE TITLE
[FEATURE] Customizable connect message and adding total points in Round-End-Summary print

### ISSUE THREAD

**Issue by Cruze03** [K4ryuu/K4-System#178]
Just as title says :P
![image](https://github.com/K4ryuu/K4-System/assets/31343375/dea9cb79-3147-46e3-98af-19cef93e40fd)

**Comment by K4ryuu** [comment]
Appreciate for the reminder ❤️

**Comment by K4ryuu** [comment]
Both has been completed and going to upload in the upcoming release.
