### ISSUE TITLE
[ENHANCEMENT] Add `TopPlacement` field to SharedApi

### ISSUE THREAD

**Issue by ivenuss** [K4ryuu/K4-System#179]
## Describe the enhancement
Add new field  `TopPlacement` to SharedApi. It should return given player placement.

## Concept structure
`K4-SharedApi.cs`

```cs
int TopPlacement { get; }
```

`PluginAPI.cs`

```cs
public int TopPlacement
{
	get
	{
		if (_player is null || !_player.IsValid || !_player.IsPlayer || _player.rankData is null)
			throw new Exception("K4-SharedAPI > TopPlacement (get) > Player is not valid or is not a player.");

		return _player.rankData.TopPlacement;
	}
}
```

**Comment by K4ryuu** [comment]
The feature has been added to the upcoming release. It is going to be uploaded when I have finished with the rest
