### ISSUE TITLE
optimize this plugin - performance issue

### ISSUE THREAD

**Issue by mayersgamer** [K4ryuu/K4-System#187]
its showing "server slow frame" more frequently with latest updates why ? 

server doesnt show this error even with 30 players on server , but once i load your plugin even with 6 players this red error apears .

**Comment by K4ryuu** [comment]
I close this issue due to I already announced remake a while ago. So its planned to remake the plugin and not continue the current version. So this issue makes no sense knowing this information.

Also with a Ryzen 4.7GHz CPU i dont see any long frame :(
