### ISSUE TITLE
[REQ] Ranks In Chat

### ISSUE THREAD

**Issue by ghostt187** [K4ryuu/K4-System#19]
**Describe the solution you'd like**
Like the scoreboard ranks it would be a good feature to have the ranks in chat when a players types a msg to be showen his rank beside his name for example: [Global Elite] K4ryuu: test123 , it would be a good feature and the rank to be colored like the color codes set at the config file

**Comment by K4ryuu** [comment]
Greetings,
Until chat messages cannot be blocked, I can add prefix to chat, but that would result in 2 messages sent sadly.
If this feature will be opted into CSS, I'm going to add it for sure.

Thank you for the feedback!

I close this issue for now, since cannot be done.

Best Regard,
K4ryuu
