### ISSUE TITLE
[FEATURE] Different color for Headshot & Special kills.

### ISSUE THREAD

**Issue by ItsCEED** [K4ryuu/K4-System#193]
![image](https://github.com/K4ryuu/K4-System/assets/20998381/010fcea6-956d-45b8-b5bd-1d928147e922)

Example, Gold/Orange for Headshot and Purple/Violet for Special Addition, and I assume another color for Unusual stuff like noscope etc.

**Comment by K4ryuu** [comment]
The plugin don't need to be modified for this.
If you open the lang folder, you find the translation files. If you edit a line for example:
`"k4.phrases.headshot": "{orange}Headshot{green}",`
This is going to color the Headshot to orange
