### ISSUE TITLE
[FEATURE] Enhanced Level Display System for User Scores

### ISSUE THREAD

**Issue by 1370533448** [K4ryuu/K4-System#196]
Is your feature request related to a problem? Please describe.
I'm always frustrated when I want to showcase user scores in a visually appealing manner, but the current level display system requires editing level names, which limits flexibility and creativity.

Describe the solution you'd like
I would like to have a level display system similar to LR extensions that showcases user scores in a Premier style. This would eliminate the need to edit level names and allow us to use labels for other functions, such as TOP 1 or VIP, as well as custom titles for players.

Describe alternatives you've considered
I have considered simply using the existing level naming system, but it does not provide the flexibility needed to highlight user achievements effectively. Another alternative could be a basic leaderboard, but it lacks the personalization and aesthetic appeal I am looking for.

Additional context
Implementing this feature would enhance user engagement by providing a more dynamic and visually appealing way to recognize player achievements. Additionally, it would allow for greater customization, making the gaming experience more enjoyable and personalized.

**Comment by 1370533448** [comment]
https://csdevs.net/resources/lr-fakerank.641/
Like him

**Comment by K4ryuu** [comment]
I dont know what are you talking about exactly as I see that you are using a translator, but if you looking for scoreboard ranks, its already developed for the plugin... Just read the readme of K4-System.

If you still cant find it: https://github.com/K4ryuu/K4-System-MMRanks
