### ISSUE TITLE
[REQ] [IDEA] New command to check your rank progress

### ISSUE THREAD

**Issue by itsAudioo** [K4ryuu/K4-System#2]
Hey I was wondering if this would be possible to implement into ranking system
lvl - command that tells you how much xp you have and how much xp you need to progress to next level.

**Comment by K4ryuu** [comment]
Greetings,
I am going to create a new design for the rank command, which is going to show the following informations on use:

- Current rank
- Current point
- Next rank
- Points until next rank
- Place in toplist

This update will be added within the upcoming days.

Best Regards,
K4ryuu

**Comment by itsAudioo** [comment]
Thats sounds amazing ‼

**Comment by K4ryuu** [comment]
The feature is implemented in the latest build.
![CleanShot 2023-11-13 at 18 14 38@2x](https://github.com/K4ryuu/K4-System/assets/104531589/a2ae2047-0640-4214-92cb-a8fa127b6a8a)

Best Regards,
K4ryuu
