### ISSUE TITLE
[BUG] SQL Failure

### ISSUE THREAD

**Issue by AxiomaticIntrusion** [K4ryuu/K4-System#200]
**Describe the bug**
Set the plugin up yesterday and connected to SQL DB, was working perfectly (restarts and all worked fine), this morning after restarting the server, I was given the error that the authentication method failed and I needed to set AllowPublicKeyRetrieval to true.

**Expected behavior**

**Logs/Screenshots**
Please attach logs or screenshots if available.
![image_2024-08-01_084242531](https://github.com/user-attachments/assets/2b5e70bc-9302-4337-8595-2ea7fb51f5b5)

**Environment (please complete the following information):**
- OS: Ubuntu 24.04
- CSS Version latest
- Plugin Version latest
- Configs [OPTIONAL depending on the context of the bug]

**Additional context**

**Comment by AxiomaticIntrusion** [comment]
Recreated a new SQL server identical to yesterdays process, results in the same error.

**Comment by K4ryuu** [comment]
The error literally says to use secure connection. This is why the "sslmode" is added to the database section, which I bet you left on "none".

Your database is configured to allow only secure connection, so set the plugin to use it.

![image](https://github.com/user-attachments/assets/3094632e-93be-46d1-a5d5-b14728c2d151)

**Comment by AxiomaticIntrusion** [comment]
My apologies, thank you very much

**Comment by K4ryuu** [comment]
> My apologies, thank you very much

No issues, don't worry about it!
Cheers mate!
