### ISSUE TITLE
[REQ]!top ranks to appear same color as they are set in config

### ISSUE THREAD

**Issue by dialupa** [K4ryuu/K4-System#22]
Hello! This might be a bug as well not sure, but I was wondering if it would be possible for the ranks that show up in the !top command to be colored the same way they are set in the ranks config? Currently they come up as lightblue(the point value shows lightblue as well) even if they are set to a different color in the ranks config and there doesn't appear to be a way to change it. The correct color shows when typing !rank but not !top.

**Comment by K4ryuu** [comment]
Greetings,
Yes. The rank colors set from the config file, but if you change it, you have to check which CSS cokor is different (there are some which is the same). You can check that on the link given in the generated ranks file.

Also after change, you have to restart the server or plugin to load new values.

**Comment by dialupa** [comment]
![rankcolor](https://github.com/K4ryuu/K4-System/assets/150990617/e2064b28-5bdc-4a41-8461-97d4dd262832)

Here is a screenshot so you see what I'm talking about. When I type !rank, it correctly shows the rank as the color I set in the config(purple in this case); but when I type !top it does not show the correct color. It show the rank as lightblue

**Comment by dialupa** [comment]
![rankcolor](https://github.com/K4ryuu/K4-System/assets/150990617/fbcd07df-cc34-49f8-8ff0-a98c1921dcd5)


Here is a screenshot so you see what I'm talking about. When I type !rank, it correctly shows the rank as the color I set in the config(purple in this case); but when I type !top it does not show the correct color. It show the rank as lightblue

**Comment by K4ryuu** [comment]
Oh, I see what are you talking about!
Today I add this feature.

**Comment by K4ryuu** [comment]
I have added the feature. You will find it in the next release.

**Comment by dialupa** [comment]
![pointsbork](https://github.com/K4ryuu/K4-System/assets/150990617/c46f5388-3cf4-41d1-be90-4c0d5d2439b3)
Here is what it looks like now, they are just showing up as white/default. Not showing up as the color :x
