### ISSUE TITLE
[BUG] Round start immediate crash (Retake)

### ISSUE THREAD

**Issue by freakexeuLow** [K4ryuu/K4-System#25]
**Describe the bug**
is described below, as soon as I unload your system, everything works again without problems....have tested it 3x as a precaution (Version 1.3.1 last stable)

**To Reproduce**
Warmup disappears after 3 seconds, then the real game begins and the bomb plan is executed, followed immediately by a crash

**Logs (Optional)**
was logged with: [https://github.com/komashchenko/AcceleratorLocal](https://github.com/komashchenko/AcceleratorLocal)
Crash Dumb File: [275b1e3d-6837-4a4e-ea1c05bb-f6900558.dmp.txt](https://github.com/K4ryuu/K4-System/files/13400677/275b1e3d-6837-4a4e-ea1c05bb-f6900558.dmp.txt)

and thanks for your work, it's amazing what is now possible after a few months :)

**Comment by K4ryuu** [comment]
Try not to load any accelerator plugins

**Comment by K4ryuu** [comment]
Greetings,
I have solved the problem and will be available in the upcoming release.
Reference: #31 

Best Regards,
K4ryuu
