### ISSUE TITLE
[BUG] Config file is not created 

### ISSUE THREAD

**Issue by GreeNyTMs** [K4ryuu/K4-System#28]
Hello, when i upload the newest K4 system, config file is not created and i cant connect it with database etc...
![image](https://github.com/K4ryuu/K4-System/assets/149469349/ced4abf6-c2b8-456c-8e25-51e037e9ed49)

**Comment by pZyk93** [comment]
Look here instead -> /game/csgo/addons/counterstrikesharp/configs/plugins

**Comment by K4ryuu** [comment]
You are in the wrong folder for that. I recommend reading the "Getting Started" section of the repo.
