### ISSUE TITLE
[BUG]!top ranks showing as incorrect color

### ISSUE THREAD

**Issue by dialupa** [K4ryuu/K4-System#29]
![283969373-c46f5388-3cf4-41d1-be90-4c0d5d2439b3](https://github.com/K4ryuu/K4-System/assets/150990617/ad13e491-d2d7-4b0e-993a-fb586401be6f)

Picture attached. Rank colors have been properly set in config. When I type !rank, the rank shows the correct color, but when I type !top the ranks are shown as the wrong color.

**Comment by K4ryuu** [comment]
Greeings,
I found the problem and will be fixed in the next release.

Thank you for the feedback!
