### ISSUE TITLE
[BUG] Errors when typing rank and when joining

### ISSUE THREAD

**Issue by ghostt187** [K4ryuu/K4-System#30]
This is the error it shows when joining the server
[errorwhenjoining.txt](https://github.com/K4ryuu/K4-System/files/13407081/errorwhenjoining.txt)

And this is when typing rank
[typingrank.txt](https://github.com/K4ryuu/K4-System/files/13407084/typingrank.txt)

**Comment by K4ryuu** [comment]
Your error contains the following line
`Unknown column 'rank' in 'field list'`


Which means that, you are not using the tables generated by K4, but you use the old SimpleRank tables. Delete your tables or use alter commands to make them the same structure.

Best Regards,
K4ryuu

**Comment by ghostt187** [comment]
if i use alter commands to make same structure will i lose the players points and if not how do i do that..
