### ISSUE TITLE
[BUG]!top still not correctly showing colors

### ISSUE THREAD

**Issue by dialupa** [K4ryuu/K4-System#32]
Hello, picture attached. When I type !top, the ranks are displayed like this. They still are not showing as the correct colors.
This is with latest release(K4-System v1.3.2) as well as CSS v62

![image](https://github.com/K4ryuu/K4-System/assets/150990617/9dd6c7c8-011b-49f1-940e-eaed9b084d92)

**Comment by K4ryuu** [comment]
The problem is being solved in the upcoming release.
Thank you for the feedback!

**Comment by jinnsTaRR** [comment]
Its now better, but not right. 
The he dont take the actuall color from the rank > See screenshot
![K4 ](https://github.com/K4ryuu/K4-System/assets/89946984/c75d08dc-c94a-4d33-b0ee-6879f82390d7)
![k4 2](https://github.com/K4ryuu/K4-System/assets/89946984/b49b0209-c6cb-4b4a-95cc-d940f794d253)



and !givepoints "SteamID64" dont work for other ids, just by myself > see screenshot

**Comment by jinnsTaRR** [comment]
> The problem is being solved in the upcoming release. Thank you for the feedback!

Its now better, but not right.
The he dont take the actuall color from the rank > See screenshot
![K4 ](https://github.com/K4ryuu/K4-System/assets/89946984/3f8abff5-ae02-4373-a48e-5b24eef302fb)
![k4 2](https://github.com/K4ryuu/K4-System/assets/89946984/38dcde57-b0bd-4407-b403-fa5a1960b658)


and !givepoints "SteamID64" dont work for other ids, just by myself > see screenshot
