### ISSUE TITLE
[BUG] Stats not recording correctly

### ISSUE THREAD

**Issue by pZyk93** [K4ryuu/K4-System#33]
**Describe the bug**
The plugin is not tracking statistics properly, and not equally for everyone. 
Some players it doesn't record anything, mostly it only tracks round wins/mvp.
On map change it can differ, and for one player it may track kills but not deaths or other stats etc.

This has been the case with the previous version and the newest version of the plugin, clean installs default config (except database ofc.)
Not sure what the cause is, but I figured I would post here to see if it was the same for more people than me.

**To Reproduce**
See above.

**Expected behavior**
I expected the stats to be tracked, kills, deaths and all the features.

**Media (Optional)**
Not the greatest example, but demonstrates what the issue is.

https://i.imgur.com/jEYEEMI.png

**Comment by K4ryuu** [comment]
This problem may be connected to #45 or #39 probably

**Comment by K4ryuu** [comment]
Was the problem solved with the mentioned other 2 issue solution?

**Comment by pZyk93** [comment]
Seems to have been resolved, it seems to track about every stat now!

**Comment by pZyk93** [comment]
Seems to have been resolved, it seems to track about every stat now from what i can tell.
