### ISSUE TITLE
[BUG] The server crashes

### ISSUE THREAD

**Issue by r821del** [K4ryuu/K4-System#36]
There are no errors, the server does not have time to turn on as it is already falling

**Comment by K4ryuu** [comment]
Are you running a retake server?

**Comment by r821del** [comment]
No

**Comment by K4ryuu** [comment]
You still have the problem after the latest release?
Do you have any additional information? 

Without any base to the problem, I'm unable to help.

Atleast try to use debug mode for your crash.

**Comment by r821del** [comment]
How to enable the layout mode?

**Comment by K4ryuu** [comment]
What layout mode?
