### ISSUE TITLE
[BUG] The next map does not collect statistics either

### ISSUE THREAD

**Issue by t4r1k58** [K4ryuu/K4-System#39]
It does not collect statistics after the map changes. Server Console Image is Attached. Sorry for the bad English.
![ssss](https://github.com/K4ryuu/K4-System/assets/151680778/d772a22b-b40b-4b20-aaa2-eb479f52161e)

**Comment by K4ryuu** [comment]
This problem may be from the new GameRule problem, which was reported by multiple users. 
The source of that is unknown yet, but I'm going to investigate it today.

Thank you for the feedback!

**Comment by K4ryuu** [comment]
The next patch is going to fix your problem.
Also note that there are settings to disable points under x amount of players and also in warmups.
