### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GravityUA** [K4ryuu/K4-System#40]
![image](https://github.com/K4ryuu/K4-System/assets/148160078/1246f23c-e8f4-40bd-988c-658a16b97609)

Is it normal that it constantly writes in the server console?

**Comment by t4r1k58** [comment]
Make sure you enter your mysql database settings in addons/counterstrikesharp/configs/plugins/k4-system/k4-system.json or check your mysql username password.

**Comment by K4ryuu** [comment]
Yes, this is normal. This means you have entered the wrong password for the database given.

**Comment by GravityUA** [comment]
![image](https://github.com/K4ryuu/K4-System/assets/148160078/76cd0fe8-3a1d-4a04-88fd-682fb5166679)

**Comment by GravityUA** [comment]
![Screenshot_1](https://github.com/K4ryuu/K4-System/assets/148160078/09bf3a9e-0f05-44cb-b0a8-e297ba95db78)
