### ISSUE TITLE
[BUG] Rank and Toplist shows different point values

### ISSUE THREAD

**Issue by chycken** [K4ryuu/K4-System#41]
Hello, I have 1 bug using the latest version of plugin and cssharp
As you see in the pic, !rank and !top shows different points for me (chickender)...It takes approx 1 min to show the same points on !top as !rank...
![aaa](https://github.com/K4ryuu/K4-System/assets/25958225/9b0a7c82-c6ed-4bd8-bcf5-4344667bf5b4)

**Comment by K4ryuu** [comment]
Most probably this problem was solved by another bug fix, but I keep this issue opened until you approve this theory of mine. That patch will be available from 1.3.4

**Comment by chycken** [comment]
thanks dude

**Comment by K4ryuu** [comment]
I have tested my newest version (1.3.4) and the problem cannot be reproduced anymore. I close the issue and shortly releasing this build. Thank you
