### ISSUE TITLE
[REQ] Reset command for the other two section 

### ISSUE THREAD

**Issue by jinnixyz** [K4ryuu/K4-System#42]
!resetmyrank and !resetrank "STEAMID" doesnt reset the !time and !stat 
IDK if its a bug or not? but i where be nice when the reset make a full reset of all

**Comment by K4ryuu** [comment]
ResetMyRank as the name also says resets only the RANK related stuff. I'm adding reset command for the other two sections also.

**Comment by jinnixyz** [comment]
Alright, youre Amazing. Keep it up 🙏🏻

**Comment by crashzk** [comment]
> ResetMyRank as the name also says resets only the RANK related stuff. I'm adding reset command for the other two sections also.

I believe it would be interesting to add the option for the administrator to choose how he will reset the players.

Something like:
- `!resetrank "SteamID64"` - Removes statistics from your games;
   - `all`- Will reset all data;
   - `exp` - Will reset data on experience points; **_(value, rank)_**
   - `stats` - Will reset statistics data; **_(kills, deaths, shoots, hits, headshots, assists, round_win, round_lose, statistics)_**
   - `playtime` - Will reset playtime data;

In other words, one option to reset all information, another to reset just the rank points, another to remove all statistics and another to remove playtime

I believe it would be interesting to even add a command to completely delete all data from the target player, some command like `!deleterank "SteamID64"`. In the case of admin access and when using it in a player, delete everything and delete it from the database.

And the `!resetmyrank` command continues to just reset the players self rank and points.

I believe this would be perfect for when working with a web interface. Where we can reset the players' ranks but still leave their hours, etc. displayed on their profile on the website.

**Comment by K4ryuu** [comment]
Great idea @crashzk, will be adding soon

**Comment by K4ryuu** [comment]
The feature has been added to latest release.
Thank you
