### ISSUE TITLE
[BUG] Collection of visual bugs

### ISSUE THREAD

**Issue by jinnixyz** [K4ryuu/K4-System#43]
![rank](https://github.com/K4ryuu/K4-System/assets/89946984/79e5fb4e-f44b-4268-83ee-55f14c52716f)

I discovered the following bugs:
1. at the maximum rank 21 / 21, the next rank is the 1 / 21 rank again
2. if you enter !top10 and see the rankings, it doesn't recognize the color in [Godlike] but transfers it to silver 1, which actually has to be the color gray
3. the ranks do not synchronize with the ranks in the tab. (I have synchronization stats on)
4. when you say !time the "Alive" and "Dead" counter doesnt work right.

**Comment by K4ryuu** [comment]
I have patched some of your reported bugs,  but some I was unable to reproduce. 
You can try the patched within the next release.

**Comment by K4ryuu** [comment]
I have patched the remaining of this issue. Next patch has them all fixed and tested.
Thank you for the patience!
