### ISSUE TITLE
[BUG] Player with 0 SteamID

### ISSUE THREAD

**Issue by skaen** [K4ryuu/K4-System#45]
css: v 61
Sometimes a player with 0 SteamID appears:

![image](https://github.com/K4ryuu/K4-System/assets/17942495/74b3064b-e022-4ac7-b683-042d2e9d3a8b)
![image](https://github.com/K4ryuu/K4-System/assets/17942495/271475d9-4e31-4af9-aee2-a273d050bc54)

**Comment by K4ryuu** [comment]
How is that possible 😆 
I will check that, but possibly a CSS bug(?)

**Comment by jinnixyz** [comment]
> css: v 61 Sometimes a player with 0 SteamID appears:
> 
> ![image](https://user-images.githubusercontent.com/17942495/284872000-74b3064b-e022-4ac7-b683-042d2e9d3a8b.png) ![image](https://user-images.githubusercontent.com/17942495/284872075-271475d9-4e31-4af9-aee2-a273d050bc54.png)

dumb question, but are they 2 bots? they name is like from bots, they have no STEAM ID.

**Comment by asdfxD** [comment]
i think they are bots.

**Comment by K4ryuu** [comment]
The problem is being solved in the next release.
Thank you for the feedback.
