### ISSUE TITLE
[BUG] disconnect lag

### ISSUE THREAD

**Issue by mrdiega** [K4ryuu/K4-System#46]
css v65
K4-System v1.3.3

Server microlag occurs when a player disconnects

**Comment by K4ryuu** [comment]
The problem can be solved by adding asynchronous tasks and the plugin won't stop to execute the client save functions.

I'm adding this within the next release tomorrow.
Thank you!

**Comment by K4ryuu** [comment]
The bug is being fixed in the next patch.
Thank you for the report.
