### ISSUE TITLE
[BUG]  Color BUG & ! command BUG        v1.3.3

### ISSUE THREAD

**Issue by jinnixyz** [K4ryuu/K4-System#47]
1. !givepoints / !resetrank doesn't work for others, only for myself> see screenshot (its another SteamID, not mine)

![k4 2](https://github.com/K4ryuu/K4-System/assets/89946984/75f8dbda-449f-466c-a350-926b61685481)

2. No matter what distance you always get long distance points

**Comment by K4ryuu** [comment]
The targeted player has to be online. 
I didn't find any problem with the targeting.

**Comment by jinnixyz** [comment]
Ahhhh ok i tryd to give Someone exp who wasnt online on Server sorry. Am 24.11.23 um 12:32 schrieb K4ryuu
                
            
            
                
                    Von: "K4ryuu" ***@***.***>Datum: 24. November 2023An: "K4ryuu/K4-System" ***@***.***>Cc: "jinnsTaRR" ***@***.***>,"Author" ***@***.***>Betreff: Re: [K4ryuu/K4-System] [BUG]  Color BUG & ! command BUG        v1.3.3 (Issue #47)
                
                
The targeted player has to be online.
I didn't find any problem with the targeting.
