### ISSUE TITLE
Huge lag [BUG]

### ISSUE THREAD

**Issue by y3request** [K4ryuu/K4-System#48]
Whenever I put this on my server, when someone connects there is a lag spike. When someone leaves there is a lag spike.
I don't know what exactly is happening, like maybe mysql server is laggy and plugin is waiting for the update.
This should be fixable if this is the cause.

1. Upload to my server restart, configure, restart
2. players join, server lags
3. remove plugin server doesnt lag.

**Expected behavior**
Players join/leave, no lag.

**Comment by K4ryuu** [comment]
Please next time do not open duplicated issue for a problem. Thank you.
