### ISSUE TITLE
I need information

### ISSUE THREAD

**Issue by sidasltu** [K4ryuu/K4-System#49]
How to connect this plugin with mine phpadmin becouse im using host at my host in config files when i start server json with connection string arent created so how to connect this plugin with mine host database ?

**Comment by sidasltu** [comment]
![image](https://github.com/K4ryuu/K4-System/assets/85897059/939b8c37-3d5f-4fd7-a9bb-c72b9f3d685f)
![image](https://github.com/K4ryuu/K4-System/assets/85897059/77e7beef-0cdb-47b3-8188-b59dcc783be1)

**Comment by K4ryuu** [comment]
Read the ReadMe file, which contains the getting started guide...

https://github.com/K4ryuu/K4-System#getting-started
