### ISSUE TITLE
[REQ] Support for rank images on the scoreboard

### ISSUE THREAD

**Issue by crashzk** [K4ryuu/K4-System#51]
Implement players' rankings to be displayed on the scoreboard based on their points.

![image](https://github.com/K4ryuu/K4-System/assets/32937653/9a51b95f-cdfe-4100-923e-635d07ebe178)
![image](https://github.com/K4ryuu/K4-System/assets/32937653/c3525d8f-602f-4030-b3ef-c8b801e16aa0)
![image](https://github.com/K4ryuu/K4-System/assets/32937653/b2642ac2-d05f-4394-bfe8-c3bea9f58f3a)

Each rank has its points configured in the plugin configuration, it would be interesting for each rank that the player reaches to show the rank he is in on the score.

To begin with, we can use the patents that are in CS2, Competitive and PREMIER and Wingman, and thus allow us to configure which patent image it will show as default.

In the future, if CS2 allows the use of FastDL, we can start creating our own patent images and using them.

**Comment by crashzk** [comment]
Path of the `.svg` images of the patents in the CS2 VPK file `pak01_dir.vpk`.

```
...csgo\panorama\images\icons\skillgroups
```

**Comment by K4ryuu** [comment]
Whenever we have access to GC/usermessages we can do that for sure

**Comment by funcgoof** [comment]
Dont add this in core plugin if u do this u might expose us to recieve  glts ban for doing this.

**Comment by crashzk** [comment]
> Dont add this in core plugin if u do this u might expose us to recieve glts ban for doing this.

And where did you get the information that Valve/CS2 is banning GLTS? She hasn't applied a ban for more than 2 years.

But I understand your concern, perhaps a separate plugin as mentioned.

**Comment by funcgoof** [comment]
> > Dont add this in core plugin if u do this u might expose us to recieve glts ban for doing this.
> 
> And where did you get the information that Valve/CS2 is banning GLTS? She hasn't applied a ban for more than 2 years.
> 
> But I understand your concern, perhaps a separate plugin as mentioned.

Last ban wave wasnt 2 years ago but just before cs2 limited release.  It just affected very small amount of the server owners. U are just blindly praying that u wont get banned while in fact it can happen any moment rules haven’t changed. Even this would be pretty innocent  plugin  it falls under falsifying players rank that player doesn’t have officially

**Comment by K4ryuu** [comment]
> Dont add this in core plugin if u do this u might expose us to recieve glts ban for doing this.

Wont be adding things to the core which are against the TOS of Steam, don't worry about that. Whenever it can be done, I will create it as a separate plugin, which can use the data of K4.

**Comment by dizelv12** [comment]
> Dont add this in core plugin if u do this u might expose us to recieve glts ban for doing this.

who cares about that? everybody using weaponpaints... so....

We want even FACEIT levels like in the CSGO times if u do these  both K4-system is gonna be the First plugin that comes in mind ;)

**Comment by K4ryuu** [comment]
The feature has been added to the plugin with both premier points (show player points) and rank images (have to have exactly the official rank order config). You have to disable follow guidelines in core.cfg for this.

The release going to be published shortly.

![CleanShot 2024-03-24 at 21 38 00@2x](https://github.com/K4ryuu/K4-System/assets/104531589/eea8190f-a5b2-45b8-aded-833ada73c7d1)

**Comment by K4ryuu** [comment]
![CleanShot 2024-03-24 at 21 41 08@2x](https://github.com/K4ryuu/K4-System/assets/104531589/c552b9f2-d75a-40dd-948d-bfb9412a7996)
