### ISSUE TITLE
[BUG] Rank points

### ISSUE THREAD

**Issue by jinnixyz** [K4ryuu/K4-System#53]
Taser kills are displayed as knife kills and are credited with knife kills points
Knife kills are not displayed at all and are not credited

"Suicide points" are not always deducted for suicide

**Comment by K4ryuu** [comment]
This was already fixed. Please use one of the latest versions.

**Comment by jinnixyz** [comment]
i use K4-System V1.3.4 and taser kill shows still Knife kill, i just tested it again 2 minutes ago :)
