### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sidasltu** [K4ryuu/K4-System#55]
Hello,
![image](https://github.com/K4ryuu/K4-System/assets/85897059/108b2b60-47d5-409c-a83b-4e812be1acc6)
in game im doenst see ranks score and other stuff but plugin is working this becouse of database ? can you help me with this ? 
![image](https://github.com/K4ryuu/K4-System/assets/85897059/5a49e31c-9eb4-4fcc-889f-068f2b7fe69d)

**Comment by sidasltu** [comment]
look like i see that its connected with database

**Comment by K4ryuu** [comment]
Greetings,
Please follow the Getting Started guide at the ReadMe. If you set up all good, the plugin saves correctly.
