### ISSUE TITLE
[BUG] Ranks doesnt saving

### ISSUE THREAD

**Issue by sidasltu** [K4ryuu/K4-System#58]
Points are saving but ranks arent its only for me ?

**Comment by skaen** [comment]
I also don't have kills, deaths saved
![image](https://github.com/K4ryuu/K4-System/assets/17942495/bfe3dc3d-7baa-4074-a374-18e208e9303e)
![image](https://github.com/K4ryuu/K4-System/assets/17942495/c00fa22c-41f9-4409-b7e9-78a0858d84c2)

**Comment by K4ryuu** [comment]
Greetings,
Database being updated on map end, disconnect, map change and so to prevent too many updates. The server's data being refreshed realtime for commands but they being fixed when your session changes.

**Comment by sidasltu** [comment]
> Greetings, Database being updated on map end, disconnect, map change and so to prevent too many updates. The server's data being refreshed realtime for commands but they being fixed when your session changes.

![image](https://github.com/K4ryuu/K4-System/assets/85897059/6a2f6f77-b430-406b-8e5b-66304d11a737)
in this foto score and rank its normal or you need more points to get rank ? one time i saw when i get silver i gues and after that its never displayed again, in game score panel same situation i see none all time but also i cannot comment for sure becouse im still working on server

**Comment by K4ryuu** [comment]
You have to level up within ranks (?). The default config first rank is from 250 points. If you go above, you get the rank. If you go under you lose it. What is the question?
