### ISSUE TITLE
[BUG] Incorrectly writes data to the database

### ISSUE THREAD

**Issue by skaen** [K4ryuu/K4-System#60]
I just noticed there were 25 kills in the database.
After playing the whole map and gaining 26 kilos per map, a change took place and after that there were 39 kills in the database.
BUT if you add 25+26 = 51 kills :)

**Comment by K4ryuu** [comment]
Hey,
I assume it is connected the errors which was represented on some events. It may be blocking code executions. However we are currently testing the next version and if all goes well shortly you all get the updates.
