### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mayersgamer** [K4ryuu/K4-System#64]
Just to mention after testing several ranking systems this one seems work better then others 😄 

Bug :

![Screenshot 2023-12-02 115916](https://github.com/K4ryuu/K4-System/assets/5068539/9b83a23a-6787-429b-a382-9acdf0fdf2b8)

!stat -kill section : seems to be broke how is it possible to have headshots more then my kills

**Comment by K4ryuu** [comment]
Greetings,
Currently the system is being rewritten with dependency injection methods with a much better code base.

**Comment by K4ryuu** [comment]
Greetings,
I close every issue, because 2.0 is released and no idea what is a current problem.
