### ISSUE TITLE
[BUG] K4 Plugin dont work with newest csssharp version

### ISSUE THREAD

**Issue by jinnixyz** [K4ryuu/K4-System#66]
Your plugin will no longer work as soon as you use the latest version of counterstrike sharp. 
when will new updates come?

**Comment by y3request** [comment]
I also confirm this
here is an error

> L 12/05/2023 - 07:04:42: "xxx<1><[U:x:xxxxxx]><CT>" say "!rank"
> Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
>    at K4ryuuSystem.K4System.OnCommandCheckRank(CCSPlayerController player, CommandInfo command) in /Users/sples/Documents/GitHub/K4-System/src/Commands.cs:line 66
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

he didnt post one so i am unsure if we had the same error

hard crash when typing !rank

**Comment by K4ryuu** [comment]
Greetings,
I close every issue, because 2.0 is released and no idea what is a current problem.
