### ISSUE TITLE
[BUG]Kills/deaths not adding or taking points with dynamic death points enabled

### ISSUE THREAD

**Issue by dialupa** [K4ryuu/K4-System#70]
![image](https://github.com/K4ryuu/K4-System/assets/150990617/82c3526a-4439-4802-be84-dec1a7ae75a8)

Hello, please see attached. I have updated to the latest cssharp version as well as k4 system v2.0.1, and kills/deaths are not giving or taking points. When I set "dynamic-death-points" to true in the config, it gives this error in console and gives no points. When I set "dynamic-death-points" to false, it gives points for kills and deaths.

**Comment by K4ryuu** [comment]
Greetings,
I’ve forgotten to add exception for that if player has 0 points, thats why. Will be fixed Today

**Comment by K4ryuu** [comment]
This also connects to #69

**Comment by K4ryuu** [comment]
The issue has been resolved and is scheduled for release in the upcoming version (V2.0.2), provided that all other outstanding issues are successfully addressed.
