### ISSUE TITLE
[QUESTION] Possible to remove the scoreboard ranks in killfeed?

### ISSUE THREAD

**Issue by jinnixyz** [K4ryuu/K4-System#72]
Is it possible to set the scoreboard rank so that it does not appear in the killfeed and only in the scoreboard? Otherwise the killfeed is very long and it doesn't look good

**Comment by K4ryuu** [comment]
Hello,
The killfeed is using the Clan tags same as the scoreboard. You have two options for that. 

Option1: You disable scoreboard ranks.
Option2: Set `cl_show_clan_in_death_notice 0` in the `server.cfg`

Best regards,
K4ryuu

**Comment by jinnixyz** [comment]
Unfortunately it doesn't work with the command cl_show_clan_in_death_notice "0" in the Server.cfg or gamemode.cfg. Do you have the option to insert this command into the plugin?

**Comment by K4ryuu** [comment]
No. You should find the CS2 equivalent for that command from CS:GO. I don't know the new one yet sadly. Try in the console if it works first.
