### ISSUE TITLE
[ENHANCEMENT] Up/Downrank Messages

### ISSUE THREAD

**Issue by jinnixyz** [K4ryuu/K4-System#76]
Possible to add an Message if someone gets an up/down rank? ( Only for the person in chat, that not everyone sees this)
"Congratulations! You Rank up to Silver 2"
"You got Deranked to Silver 1"

**Comment by K4ryuu** [comment]
Greetings,
You are right, I've forgotten to add that from old version to the remake. Thank you for the info haha!
I add it shortly.

**Comment by K4ryuu** [comment]
I have added the feature to the upcoming release (V2.0.2), which will be published upon all problem is solved.
