### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bespredel1337** [K4ryuu/K4-System#78]
**Describe the bug**

**To Reproduce**
1. update plugin from 2.0.1 to 2.0.2
CounterStrikesharp v110
error log -

[39;49m[37m20:51:27[39;49m[39;49m[30m [[39;49m[39;49m[37m[39;49m[37m[41mEROR[39;49m[39;49m[30m] (cssharp:[39;49m[39;49m[37mCore[39;49m[39;49m[30m) [39;49m[39;49m[37mError invoking callback[39;49m
[39;49m[37mSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.[39;49m
[39;49m[37m ---> System.NullReferenceException: Object reference not set to an instance of an object.[39;49m
[39;49m[37m   at CounterStrikeSharp.API.Core.Application.OnCSSPluginCommand(CCSPlayerController caller, CommandInfo info) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Application.cs:line 128[39;49m
[39;49m[37m   at CounterStrikeSharp.API.Modules.Utils.CommandUtils.<>c__DisplayClass0_0.<AddStandaloneCommand>b__0(Int32 i, IntPtr ptr) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Utils/StandaloneCommand.cs:line 80[39;49m
[39;49m[37m   at InvokeStub_Action`2.Invoke(Object, Object, IntPtr*)[39;49m
[39;49m[37m   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)[39;49m
[39;49m[37m   --- End of inner exception stack trace ---[39;49m
[39;49m[37m   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)[39;49m
[39;49m[37m   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)[39;49m
[39;49m[37m   at System.Delegate.DynamicInvokeImpl(Object[] args)[39;49m
[39;49m[37m   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 71[39;49m

**Comment by K4ryuu** [comment]
V2.0.2 is CSS 112 or above only.
