### ISSUE TITLE
[BUG] Promote/Demote messages are displayed twice or more

### ISSUE THREAD

**Issue by jinnixyz** [K4ryuu/K4-System#79]
Promote/Demote messages are displayed twice or more see screenshot
![k4](https://github.com/K4ryuu/K4-System/assets/89946984/d5165d62-6fba-49ef-90f8-09e9308cf01f)

**Comment by K4ryuu** [comment]
wtf... 
I will check that shortly haha

**Comment by jinnixyz** [comment]
> wtf... I will check that shortly haha

The error is still there, have you checked? K4-System v2.0.3

**Comment by K4ryuu** [comment]
Greetings,
The latest pre-release has fixed the problem most probably. Please check it out and give me a feedback or re-open the issue.

Thank you very much!
