### ISSUE TITLE
[REQ] Permission list for each rank

### ISSUE THREAD

**Issue by K4ryuu** [K4ryuu/K4-System#80]
This could support external sources of benefits. More HP, defuse kit or so.

Also should create example for external benefit.

**Comment by jason20240318** [comment]
Hi, is this permission list completed and opened ? how to use this function ?

**Comment by K4ryuu** [comment]
![CleanShot 2024-03-25 at 14 16 12@2x](https://github.com/K4ryuu/K4-System/assets/104531589/55617bf0-53b1-4023-aeba-60b7b8f9cf02)

This is a great example of using custom permissions for a rank. Those that you add here are visible if people check !ranks, because it lists all rank and if they select a rank that lists the permissions they get.

**Comment by jason20240318** [comment]
Great thanks. For example, if I want to set the second level to 101hp and the third level to 102hp, how should I configure it?

**Comment by K4ryuu** [comment]
You create a plugin that does plus hp for permissions, then apply the permission to the rank in the config I sent. x)
You can do whatever you want in your custom plugins and apply them through permissions for ranks.

**Comment by jason20240318** [comment]
Can you make this plugin for me , you can give me a price , I'll pay for it .

**Comment by K4ryuu** [comment]
Contact me on Discord.
The name is k4ryuu
The server is https://discord.gg/DT9VDVhMJX
