### ISSUE TITLE
[BUG] Server Crash with another plugin

### ISSUE THREAD

**Issue by jinnixyz** [K4ryuu/K4-System#81]
With the latest version of this plugin: https://github.com/NockyCZ/CS2_BombsitesRestrict the server crashs?
The bomb is thrown away as soon as you want to plant the bomb on a blocked spot. I think it has to do with the fact that you get points for planting a bomb but it is then canceled by the bomb drop, I deleted your plugin and the other plugin worked. Would it be possible to adapt this so that you can use both plugins at the same time? I don't want to use any other ranking system, I'm very happy with yours. The other plugin is also very important. I'm not sure which author has to edit this, so I reported it to both of you. There were no problems with the old version of the other plugin. If it's not part of your duties then I'm sorry

**Comment by K4ryuu** [comment]
Greetings,
Im not sure about why would it be incompatible but I will check at the next patch.

**Comment by jinnixyz** [comment]
> Greetings, Im not sure about why would it be incompatible but I will check at the next patch.

I just tried another rank pluginto look, and this crashes the server too in combination with the other plugin.
