### ISSUE TITLE
[BUG] Install does not create config

### ISSUE THREAD

**Issue by pcace** [K4ryuu/K4-System#84]
Hi there, i am curiouse to try your plugin, but cannot get it to run since a config file is not created on the first run. 
Any idea where the problem could be? 
<img width="653" alt="Bildschirmfoto 2023-12-15 um 12 37 08" src="https://github.com/K4ryuu/K4-System/assets/1011875/beb7b264-0aa5-400e-b3a9-678f634521d9">

**Comment by K4ryuu** [comment]
CSS Version?

**Comment by pcace** [comment]
v126. updated yesterday

**Comment by pcace** [comment]
i see that it does actually load the plugin, but failes due to the not configured mysql:

2023-12-15 12:43:33.777 +01:00 [EROR] plugin:K4-System Connection to the MySQL database failed: Unable to connect to any of the specified MySQL hosts.
2023-12-15 12:43:33.793 +01:00 [INFO] plugin:K4-System Initializing 'ModuleRank'
2023-12-15 12:43:33.991 +01:00 [INFO] plugin:K4-System Initializing 'ModuleStat'
2023-12-15 12:43:33.997 +01:00 [INFO] plugin:K4-System Initializing 'ModuleTime'


but since there is no config file its hard to make it work ;)

**Comment by K4ryuu** [comment]
I just tested it with 124, it generates perfectly.

**Comment by pcace** [comment]
can you post an example config file including filename and location? than i can try to make it work manually

**Comment by K4ryuu** [comment]
csgo/addons/counterstrikesharp/configs/plugins/K4-System/[K4-System.json](https://github.com/K4ryuu/K4-System/files/13684821/K4-System.json)

**Comment by pcace** [comment]
Hi there, manually adding it worked! Thanks!
