### ISSUE TITLE
[BUG] DarkBlue Color not working

### ISSUE THREAD

**Issue by asdfxD** [K4ryuu/K4-System#86]
Idk if sharp issue or plugin issue but DarkBlue color does not work.

![20231216170108_1](https://github.com/K4ryuu/K4-System/assets/24253340/8dd3fb47-6964-411c-a4dc-9cf6441cbe0e)

**Comment by K4ryuu** [comment]
The problem has been fixed. Thank you for the feedback.
The upcoming release will contain this patch.
