### ISSUE TITLE
[BUG] Rounds win, rounds lose, kda bug

### ISSUE THREAD

**Issue by sdg12321** [K4ryuu/K4-System#88]
[BUG] Rounds win, rounds lose, kda 

0 value in db.

![image](https://github.com/K4ryuu/K4-System/assets/151413805/ae63b84d-ebd4-466a-b31b-2866c287c4d0)

**Comment by K4ryuu** [comment]
Greetings,
I have fixed (and tested) all of the stats in the current patch. It will be released shortly (2.0.6).

Thank you for the feedback!
