### ISSUE TITLE
[BUG] Dynamic Points

### ISSUE THREAD

**Issue by TianxSky** [K4ryuu/K4-System#89]
Victim (4000 pts):
![image](https://github.com/K4ryuu/K4-System/assets/41808115/d255de52-c84e-49b4-9a8c-b9bef46afd3e)
Attacke (11000 pts)r:
![image](https://github.com/K4ryuu/K4-System/assets/41808115/9488016c-4d1a-4a86-aeb0-d446e2117593)
Dynamic points config:
```json
"dynamic-death-points": true,
    "dynamic-death-points-max-multiplier": 5,
    "dynamic-death-points-min-multiplier": 0.5
    "death": -10,
    "kill": 10,
```

**Comment by TianxSky** [comment]
and yeah sometimes ppl get dynamic kills points but not death points

**Comment by K4ryuu** [comment]
Greetings,
The bug has been fixed and will be released with the upcoming release.
Thank you!
