### ISSUE TITLE
[ENHANCEMENT] !ranks for list of all ranks

### ISSUE THREAD

**Issue by jinnixyz** [K4ryuu/K4-System#91]
Possible to add !ranks so that all players on the server can see what ranks there are and how much XP you need for them?

**Comment by K4ryuu** [comment]
Greetings,
Great idea, but what if there are 20 ranks? Should it print 20 lines of information together? Or maybe it could use chat menu?

**Comment by jinnixyz** [comment]
Chat Menu 👍🏼

**Comment by K4ryuu** [comment]
![CleanShot 2023-12-28 at 23 01 29@2x](https://github.com/K4ryuu/K4-System/assets/104531589/bdee2971-30d2-48c2-a737-2d0585c7226a)

The feature has been implemented. Thank you very much!
It will be available in the next release.
