### ISSUE TITLE
[REQ] Top Tags

### ISSUE THREAD

**Issue by TianxSky** [K4ryuu/K4-System#92]
Make !top commands show top 10, and then for top 10 instead of their rank tags, use Top #1, Top #2, #Top #3, Top #4, Top #5 etc..

**Comment by K4ryuu** [comment]
Greetings,
Your idea is cool, but Im not sure about the new max length of clan tags. What if someone has a rank and i want to add top before that, so they are both visible and it cannot fit into the length limit?

Also next time watch out for that if you use plain hashtag with a number, you mention other issues in the repository haha

Thanks for the idea and Im looking forward for you answer

**Comment by TianxSky** [comment]
I mean add an option to show leaderboard rankings instead of rank 
for a custom range.
And shows a custom name with string.replace({rank}, rank)
e.g. Top {rank} to Top 1

**Comment by TianxSky** [comment]
#98 is a better approach

**Comment by K4ryuu** [comment]
Greetings,
I'm closing this issue due to duplicated issues about the feature.
We can talk about this feature further at #98 

Thank you!
