### ISSUE TITLE
[BUG] points-for-bots: false - not working properly

### ISSUE THREAD

**Issue by csportalsk** [K4ryuu/K4-System#93]
```
"statistic-settings": {
    "stats-for-bots": false,
    "warmup-stats": false,
    "minimum-players": 2
  },
  "rank-settings": {
    "points-for-bots": false,
    "warmup-points": false,
    "ffa-mode": true,
    "round-end-points": false,
    "minimum-players": 2,
    "scoreboard-ranks": true,
    "scoreboard-score-sync": true,
    "vip-multiplier": 1.25,
    "dynamic-death-points": false,
    "dynamic-death-points-max-multiplier": 5,
    "dynamic-death-points-min-multiplier": 0.5
  },
```
With this settings I still get + point for killing BOT.

**Comment by K4ryuu** [comment]
Even if you set points for bots, the minimum real players applies also.

**Comment by inFqm** [comment]
On the opposite, I get points when minimum-players is set to "1" but NO kills are recorded.

**Comment by K4ryuu** [comment]
Greetings,
The reported bug has been fixed and will be available in the upcoming release.

> On the opposite, I get points when minimum-players is set to "1" but NO kills are recorded.

This however makes no sense to me. If you want something else to be also fixed, please try to describe your problem in an understandable way and open an issue for it. Thank you!

Best Regards,
K4ryuu
