### ISSUE TITLE
Added Ru Lang

### ISSUE THREAD

**Issue by ezekutor** [K4ryuu/K4-System#96]
[ru.json](https://github.com/K4ryuu/K4-System/files/13795523/ru.json)

**Comment by K4ryuu** [comment]
Unfortunately, the Russian language has already been added by ViTamin and can be found here: [ru.json](https://github.com/K4ryuu/K4-System/blob/dev/src/lang/ru.json). It will be included in the upcoming patch release soon. Thank you for your time and effort!
