### ISSUE TITLE
[REQ] Conditional Requirements for Ranks

### ISSUE THREAD

**Issue by TianxSky** [K4ryuu/K4-System#98]
Alternative ranking inputs for rank.json:
Rank tags based on player's actual placement in the leaderboard and assign them tags accordingly.
e.g. In the points property use “#20” so player's have to be in the Top 20 
for that rank

**Comment by K4ryuu** [comment]
Greetings,
Just to clarify your idea: Do you want to add conditions to meet to get a rank? One of the mentioned condition by you is the place in the toplist. Am I getting it correctly? 

Appreciate your idea!

**Comment by weeestar** [comment]
It would be so awesome!

Like ranking position for TOP99 (eg. 7th - [name]) 
Top200 tag for top199 (eg. top200 - [name])

and so on... maybe top200, top300 and top1000 would be enough to motivate our soldiers

**Comment by weeestar** [comment]
Any news about it? :)

**Comment by K4ryuu** [comment]
Toplist placement can now be displayed on scoreboard with new settings from the upcoming release!
